### ISSUE TITLE
Problem accessing id of EntityWithCustomId when using select or all

### ISSUE THREAD

**Issue by loidedano** [fwbrasil/activate#161]
I have an entity with custom id of vector byte (it has its own encoder to convert between vector byte to string)

The problem is when I access the id of the entity after a query using select or all.
For example:
val list = transactional{ all[ model.EIS ] }
println("id = " + list(0).id)

The error produced is:
java.lang.String cannot be cast to scala.collection.immutable.Vector

Actually you don't even have to access the id property, accessing any property of the entity will produce the same error.

However, if I use byId:
val entity = transactional { byId[ model.EIS ](actualId) }
 val map = transactional { entity.map(_.toMap) }
 println("\n\n******got this id =" + entity.get.id)

I can access it without error.
This problem does not seem to happen if the entity is only Entity (not EntityWithCustomId) even if it has fields of type vector byte.

**Comment by fwbrasil** [comment]
It is the same issue as https://github.com/fwbrasil/activate/issues/164. Lets track the fix there.
