### ISSUE TITLE
running  jar  application with activate-framework

### ISSUE THREAD

**Issue by claytonsilva** [fwbrasil/activate#180]
i get this error when run with java -jar (my application.jar) with activate 

![captura de tela 2015-06-03 as 18 28 59](https://cloud.githubusercontent.com/assets/2955087/7971919/d1bc8618-0a1e-11e5-9bc3-bb834e8f0a97.png)

**Comment by fwbrasil** [comment]
Is it a fat jar? Is activate in the class path?

**Comment by claytonsilva** [comment]
nervermind... i'm using sbt/one-jar  and i have this problem.. solved changing to sbt-assembly

https://github.com/sbt/sbt-assembly

**Comment by claytonsilva** [comment]
explain the problem:

i need one jar to run with taskrunner application, so i build this application with one-jar assembly.

but, one-jar don't work with activate very well, but change the assembly to sbt-assembly... my problem is solved.
